import { Category, Customer, Expense, Product, StoreSettings, Supplier, AppUser, UserRole, UserPermissions } from '../types';

export const initialCategories: Category[] = [
  { id: 1, name: 'خضر وفواكه (بالميزان)', icon: 'Apple', color: '#10B981' },
  { id: 2, name: 'ألبان وأجبان', icon: 'Milk', color: '#3B82F6' },
  { id: 3, name: 'ألبان وأجبان وبيض', icon: 'Egg', color: '#0284C7' },
  { id: 4, name: 'مواد غذائية عامة وبقوليات', icon: 'Package', color: '#F59E0B' },
  { id: 5, name: 'مشروبات وعصائر', icon: 'CupSoda', color: '#8B5CF6' },
  { id: 6, name: 'زيوت وسكريات وتوابل', icon: 'Flame', color: '#EF4444' },
  { id: 7, name: 'معلبات ومصبرات', icon: 'Layers', color: '#EC4899' },
  { id: 8, name: 'مخبوزات وحلويات', icon: 'Cookie', color: '#D97706' },
  { id: 9, name: 'منظفات ومستلزمات منزلية', icon: 'Sparkles', color: '#06B6D4' },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 1,
    name: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    phone: '0550123456',
    address: 'المنطقة الصناعية - الجزائر',
    company: 'الهضاب ديستريبسيون',
    totalPurchases: 285000,
    totalDebt: 35000,
    totalPaid: 250000,
    notes: 'مورد رئيسي للزيوت والسكر والفرينة والمعجنات',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'سوق الجملة للخضر والفواكه الطازجة',
    phone: '0661987654',
    address: 'سوق الجملة حطاطبة',
    company: 'تعاونية الفلاحين',
    totalPurchases: 140000,
    totalDebt: 0,
    totalPaid: 140000,
    notes: 'توصيل يومي صباحاً للخضار والفواكه بالميزان',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'ملبنة ومصنع السلام للألبان',
    phone: '0770456789',
    address: 'المنطقة الفلاحية الشرقية',
    company: 'ألبان السلام',
    totalPurchases: 95000,
    totalDebt: 12000,
    totalPaid: 83000,
    notes: 'مورد الحليب الطازج واللبن والياغورت والأجبان',
    createdAt: new Date().toISOString(),
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 1,
    name: 'محمد بن علي (زبون دائم)',
    phone: '0555112233',
    address: 'حي الشهداء، عمارة 4',
    totalSpent: 42500,
    totalDebt: 3200,
    totalPaid: 39300,
    lastPurchaseDate: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    notes: 'يسدد ديونه في نهاية كل شهر بانتظام',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'كريم بلحاج',
    phone: '0666445566',
    address: 'شارع الاستقلال رقم 12',
    totalSpent: 28000,
    totalDebt: 6500,
    totalPaid: 21500,
    lastPurchaseDate: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0],
    notes: 'باقي عليه جزء من فاتورة الأسبوع الماضي',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'أحمد قادري',
    phone: '0777889900',
    address: 'حي النور فيلا 8',
    totalSpent: 19500,
    totalDebt: 0,
    totalPaid: 19500,
    lastPurchaseDate: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    notes: 'دفع نقدي دائماً',
    createdAt: new Date().toISOString(),
  },
];

export const initialProducts: Product[] = [
  // --- Scale / Weight Items (خضر وفواكه وأجبان بالميزان) ---
  {
    id: 1,
    name: 'طماطم طازجة محلية',
    category: 'خضر وفواكه (بالميزان)',
    barcode: '200001',
    unit: 'kg',
    stockQuantity: 45.5,
    minStockAlert: 10,
    costPrice: 90,
    sellingPrice: 130,
    profitMargin: 44.4,
    supplierId: 2,
    supplierName: 'سوق الجملة للخضر والفواكه الطازجة',
    isScaleItem: true,
    purchaseDate: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 6).toISOString().split('T')[0],
    notes: 'طماطم نوعية ممتازة للسلطة والطبخ',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'بطاطا ممتازة للطبخ والقلي',
    category: 'خضر وفواكه (بالميزان)',
    barcode: '200002',
    unit: 'kg',
    stockQuantity: 120.0,
    minStockAlert: 25,
    costPrice: 65,
    sellingPrice: 90,
    profitMargin: 38.4,
    supplierId: 2,
    supplierName: 'سوق الجملة للخضر والفواكه الطازجة',
    isScaleItem: true,
    purchaseDate: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 25).toISOString().split('T')[0],
    notes: 'بطاطا مغسولة ونظيفة',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'بصل أحمر جاف',
    category: 'خضر وفواكه (بالميزان)',
    barcode: '200003',
    unit: 'kg',
    stockQuantity: 38.0,
    minStockAlert: 15,
    costPrice: 55,
    sellingPrice: 80,
    profitMargin: 45.4,
    supplierId: 2,
    supplierName: 'سوق الجملة للخضر والفواكه الطازجة',
    isScaleItem: true,
    purchaseDate: new Date(Date.now() - 86400000 * 4).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 40).toISOString().split('T')[0],
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'تفاح أحمر محلي نوع أول',
    category: 'خضر وفواكه (بالميزان)',
    barcode: '200004',
    unit: 'kg',
    stockQuantity: 28.5,
    minStockAlert: 8,
    costPrice: 280,
    sellingPrice: 390,
    profitMargin: 39.2,
    supplierId: 2,
    supplierName: 'سوق الجملة للخضر والفواكه الطازجة',
    isScaleItem: true,
    purchaseDate: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 14).toISOString().split('T')[0],
    notes: 'تفاح حلو مقرمش',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'موز مستورد فاخر',
    category: 'خضر وفواكه (بالميزان)',
    barcode: '200005',
    unit: 'kg',
    stockQuantity: 18.0,
    minStockAlert: 6,
    costPrice: 320,
    sellingPrice: 420,
    profitMargin: 31.25,
    supplierId: 2,
    supplierName: 'سوق الجملة للخضر والفواكه الطازجة',
    isScaleItem: true,
    purchaseDate: new Date(Date.now() - 86400000).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 4).toISOString().split('T')[0],
    notes: 'يجب المتابعة لقرب انتهاء الصلاحية والاصفرار',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'جبن أحمر غودا (بالوزن)',
    category: 'ألبان وأجبان',
    barcode: '200006',
    unit: 'kg',
    stockQuantity: 12.4,
    minStockAlert: 3,
    costPrice: 1200,
    sellingPrice: 1650,
    profitMargin: 37.5,
    supplierId: 3,
    supplierName: 'ملبنة ومصنع السلام للألبان',
    isScaleItem: true,
    purchaseDate: new Date(Date.now() - 86400000 * 10).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 60).toISOString().split('T')[0],
    notes: 'قالب جبن هولندي مقطع حسب طلب الزبون بالوزن',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: 'زيتون أخضر متبل بالميزان',
    category: 'مواد غذائية عامة وبقوليات',
    barcode: '200007',
    unit: 'kg',
    stockQuantity: 15.0,
    minStockAlert: 4,
    costPrice: 450,
    sellingPrice: 650,
    profitMargin: 44.4,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: true,
    purchaseDate: new Date(Date.now() - 86400000 * 8).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 90).toISOString().split('T')[0],
    notes: 'متبل بالهريسة والزعتر والليمون',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- Packaged Items (قطعة / علبة مع باركود قياسي) ---
  {
    id: 99,
    name: 'بيض طازج (طبق / كرتونة 30 بيضة)',
    category: 'ألبان وأجبان وبيض',
    barcode: '6131234567901',
    unit: 'carton',
    stockQuantity: 25,
    minStockAlert: 5,
    costPrice: 420,
    sellingPrice: 480,
    profitMargin: 14.28,
    supplierId: 3,
    supplierName: 'ملبنة ومصنع السلام للألبان',
    isScaleItem: false,
    purchaseDate: new Date().toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 20).toISOString().split('T')[0],
    notes: 'قابل للبيع بالكرتونة (30 بيضة) أو بالحبة المفردة',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 100,
    name: 'حليب معقم (كرتونة 10 لتر / 10 أكياس)',
    category: 'ألبان وأجبان وبيض',
    barcode: '6131234567904',
    unit: 'carton',
    stockQuantity: 18,
    minStockAlert: 4,
    costPrice: 950,
    sellingPrice: 1100,
    profitMargin: 15.78,
    supplierId: 3,
    supplierName: 'ملبنة ومصنع السلام للألبان',
    isScaleItem: false,
    purchaseDate: new Date().toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 10).toISOString().split('T')[0],
    notes: 'قابل للبيع بالكرتونة أو بالكيس المفرد',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 101,
    name: 'مشروب غازي كوكاكولا (كرتونة 6 علب)',
    category: 'مشروبات وعصائر',
    barcode: '6131234567903',
    unit: 'carton',
    stockQuantity: 30,
    minStockAlert: 6,
    costPrice: 280,
    sellingPrice: 340,
    profitMargin: 21.42,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date().toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 180).toISOString().split('T')[0],
    notes: 'قابل للبيع بالكرتونة أو بالعلبة المفردة',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 102,
    name: 'مياه معدنية (كرتونة 6 قارورات 1.5 لتر)',
    category: 'مشروبات وعصائر',
    barcode: '6131234567902',
    unit: 'carton',
    stockQuantity: 40,
    minStockAlert: 10,
    costPrice: 150,
    sellingPrice: 180,
    profitMargin: 20.0,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date().toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 365).toISOString().split('T')[0],
    notes: 'قابل للبيع بالكرتونة أو بالقارورة المفردة',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: 'زيت المائدة عافية 5 لتر',
    category: 'زيوت وسكريات وتوابل',
    barcode: '6131234567890',
    unit: 'piece',
    stockQuantity: 34,
    minStockAlert: 10,
    costPrice: 580,
    sellingPrice: 650,
    profitMargin: 12.06,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 15).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 365).toISOString().split('T')[0],
    notes: 'قارورة 5 لتر أصلية',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    name: 'سكر أبيض ناعم 1 كغ',
    category: 'زيوت وسكريات وتوابل',
    barcode: '6131234567891',
    unit: 'pack',
    stockQuantity: 85,
    minStockAlert: 20,
    costPrice: 85,
    sellingPrice: 100,
    profitMargin: 17.65,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 12).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 500).toISOString().split('T')[0],
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 10,
    name: 'قهوة مطحونة فاميكو 250غ',
    category: 'مواد غذائية عامة وبقوليات',
    barcode: '6131234567892',
    unit: 'piece',
    stockQuantity: 42,
    minStockAlert: 12,
    costPrice: 220,
    sellingPrice: 270,
    profitMargin: 22.7,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 20).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 200).toISOString().split('T')[0],
    notes: 'خلطة سبيسيال إكسترا',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 11,
    name: 'حليب معقم كامل الدسم 1 لتر',
    category: 'ألبان وأجبان',
    barcode: '6131234567893',
    unit: 'pack',
    stockQuantity: 50,
    minStockAlert: 15,
    costPrice: 95,
    sellingPrice: 120,
    profitMargin: 26.3,
    supplierId: 3,
    supplierName: 'ملبنة ومصنع السلام للألبان',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 3).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 45).toISOString().split('T')[0],
    notes: 'معقم UHT',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 12,
    name: 'ياغورت ممزوج بالفواكه (علبة 4 قطع)',
    category: 'ألبان وأجبان',
    barcode: '6131234567894',
    unit: 'pack',
    stockQuantity: 18,
    minStockAlert: 10,
    costPrice: 110,
    sellingPrice: 140,
    profitMargin: 27.27,
    supplierId: 3,
    supplierName: 'ملبنة ومصنع السلام للألبان',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 4).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 8).toISOString().split('T')[0], // Near expiry alert demo
    notes: 'تنبيه: اقتربت الصلاحية',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 13,
    name: 'طماطم مصبرة كاب 800غ',
    category: 'معلبات ومصبرات',
    barcode: '6131234567895',
    unit: 'piece',
    stockQuantity: 60,
    minStockAlert: 15,
    costPrice: 210,
    sellingPrice: 260,
    profitMargin: 23.8,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 30).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 300).toISOString().split('T')[0],
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 14,
    name: 'تونة زيت نباتي إيزابيل 160غ',
    category: 'معلبات ومصبرات',
    barcode: '6131234567896',
    unit: 'piece',
    stockQuantity: 4, // Low stock demo!
    minStockAlert: 12,
    costPrice: 165,
    sellingPrice: 210,
    profitMargin: 27.27,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 40).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 400).toISOString().split('T')[0],
    notes: 'مخزون منخفض جداً بحاجة للطلب',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 15,
    name: 'مكرونة رندة سباغيتي 500غ',
    category: 'مواد غذائية عامة وبقوليات',
    barcode: '6131234567897',
    unit: 'pack',
    stockQuantity: 70,
    minStockAlert: 20,
    costPrice: 55,
    sellingPrice: 75,
    profitMargin: 36.36,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 18).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 360).toISOString().split('T')[0],
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 16,
    name: 'مياه معدنية لالة خديجة 1.5 لتر',
    category: 'مشروبات وعصائر',
    barcode: '6131234567898',
    unit: 'piece',
    stockQuantity: 120,
    minStockAlert: 30,
    costPrice: 32,
    sellingPrice: 45,
    profitMargin: 40.6,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 360).toISOString().split('T')[0],
    notes: 'حزمة أو قارورة فردية',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 17,
    name: 'مشروب غازي كوكاكولا 1 لتر',
    category: 'مشروبات وعصائر',
    barcode: '6131234567899',
    unit: 'piece',
    stockQuantity: 48,
    minStockAlert: 15,
    costPrice: 110,
    sellingPrice: 140,
    profitMargin: 27.27,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 7).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 180).toISOString().split('T')[0],
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 18,
    name: 'مسحوق غسيل أوموماتيك 3 كغ',
    category: 'منظفات ومستلزمات منزلية',
    barcode: '6131234567800',
    unit: 'pack',
    stockQuantity: 2, // Low stock demo!
    minStockAlert: 8,
    costPrice: 620,
    sellingPrice: 780,
    profitMargin: 25.8,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 25).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 700).toISOString().split('T')[0],
    notes: 'للغسالات الأوتوماتيكية',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 19,
    name: 'بسكويت شوكولاتة ماكسي 120غ',
    category: 'مخبوزات وحلويات',
    barcode: '6131234567801',
    unit: 'piece',
    stockQuantity: 55,
    minStockAlert: 15,
    costPrice: 45,
    sellingPrice: 60,
    profitMargin: 33.3,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 10).toISOString().split('T')[0],
    expiryDate: new Date(Date.now() + 86400000 * 120).toISOString().split('T')[0],
    notes: '',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 20,
    name: 'توابل رأس الحانوت فاخرة (علبة 100غ)',
    category: 'زيوت وسكريات وتوابل',
    barcode: '6131234567802',
    unit: 'box',
    stockQuantity: 30,
    minStockAlert: 10,
    costPrice: 90,
    sellingPrice: 130,
    profitMargin: 44.4,
    supplierId: 1,
    supplierName: 'مؤسسة الهضاب لتوزيع المواد الغذائية',
    isScaleItem: false,
    purchaseDate: new Date(Date.now() - 86400000 * 45).toISOString().split('T')[0], // Stagnant candidate
    expiryDate: new Date(Date.now() + 86400000 * 300).toISOString().split('T')[0],
    notes: 'خلطة تقليدية معطرة',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 1,
    title: 'فاتورة الكهرباء للمحل ومبردات الألبان',
    category: 'electricity',
    categoryNameAr: 'كهرباء ومياه',
    amount: 14500,
    date: new Date(Date.now() - 86400000 * 5).toISOString().split('T')[0],
    notes: 'فاتورة سونلغاز ثلاثي أول',
    paidBy: 'المدير',
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    title: 'إيجار المحل التجاري الشهري',
    category: 'rent',
    categoryNameAr: 'إيجار المحل',
    amount: 45000,
    date: new Date(Date.now() - 86400000 * 12).toISOString().split('T')[0],
    notes: 'إيجار شهر كامل لصاحب العقار',
    paidBy: 'المدير',
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    title: 'أكياس تسوق بلاستيكية ومستلزمات تغليف',
    category: 'packaging',
    categoryNameAr: 'تغليف وأكياس',
    amount: 3500,
    date: new Date(Date.now() - 86400000 * 2).toISOString().split('T')[0],
    notes: 'شراء كرتون أكياس ميزان وأكياس كاشير',
    paidBy: 'الكاشير',
    createdAt: new Date().toISOString(),
  },
  {
    id: 4,
    title: 'صيانة ميزان إلكتروني ومبرد الخضر',
    category: 'maintenance',
    categoryNameAr: 'صيانة ونظافة',
    amount: 5000,
    date: new Date(Date.now() - 86400000 * 7).toISOString().split('T')[0],
    notes: 'معايرة وإصلاح محرك التبريد',
    paidBy: 'المدير',
    createdAt: new Date().toISOString(),
  },
];

export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, UserPermissions> = {
  admin: {
    canAccessPos: true,
    canAccessDashboard: true,
    canAccessScale: true,
    canManageProducts: true,
    canManagePurchases: true,
    canAccessDebts: true,
    canAccessCustomers: true,
    canAccessSuppliers: true,
    canManageExpenses: true,
    canViewProfits: true,
    canAccessStagnantExpiry: true,
    canAccessInvoices: true,
    canAccessReports: true,
    canManageUsers: true,
    canManageSettings: true,
    canDeleteSales: true,
    canApplyDiscount: true,
  },
  cashier: {
    canAccessPos: true,
    canAccessDashboard: false,
    canAccessScale: true,
    canManageProducts: false,
    canManagePurchases: false,
    canAccessDebts: false,
    canAccessCustomers: false,
    canAccessSuppliers: false,
    canManageExpenses: false,
    canViewProfits: false,
    canAccessStagnantExpiry: false,
    canAccessInvoices: false,
    canAccessReports: false, // مغلق تلقائياً لحجب التقارير الشاملة عن الكاشير
    canManageUsers: false,
    canManageSettings: false,
    canDeleteSales: false,
    canApplyDiscount: true,
  },
  employee: {
    canAccessPos: false,
    canAccessDashboard: false,
    canAccessScale: false,
    canManageProducts: true,
    canManagePurchases: true,
    canAccessDebts: false,
    canAccessCustomers: false,
    canAccessSuppliers: true,
    canManageExpenses: false,
    canViewProfits: false,
    canAccessStagnantExpiry: true,
    canAccessInvoices: false,
    canAccessReports: false,
    canManageUsers: false,
    canManageSettings: false,
    canDeleteSales: false,
    canApplyDiscount: false,
  },
};

export const initialUsers: AppUser[] = [
  {
    id: 1,
    username: 'admin',
    fullName: 'مدير المحل (المسؤول العام)',
    role: 'admin',
    pinCode: '1234',
    permissions: {
      canAccessPos: true,
      canAccessDashboard: true,
      canAccessScale: true,
      canManageProducts: true,
      canManagePurchases: true,
      canAccessDebts: true,
      canAccessCustomers: true,
      canAccessSuppliers: true,
      canManageExpenses: true,
      canViewProfits: true,
      canAccessStagnantExpiry: true,
      canAccessInvoices: true,
      canAccessReports: true,
      canManageUsers: true,
      canManageSettings: true,
      canDeleteSales: true,
      canApplyDiscount: true,
    },
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 2,
    username: 'cashier1',
    fullName: 'أحمد - كاشير الصباح',
    role: 'cashier',
    pinCode: '0000',
    permissions: {
      canAccessPos: true,
      canAccessDashboard: false,
      canAccessScale: true,
      canManageProducts: false,
      canManagePurchases: false,
      canAccessDebts: false,
      canAccessCustomers: false,
      canAccessSuppliers: false,
      canManageExpenses: false,
      canViewProfits: false,
      canAccessStagnantExpiry: false,
      canAccessInvoices: false,
      canAccessReports: false,
      canManageUsers: false,
      canManageSettings: false,
      canDeleteSales: false,
      canApplyDiscount: true,
    },
    isActive: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    username: 'employee1',
    fullName: 'سمير - أمين المخزن والمشتريات',
    role: 'employee',
    pinCode: '1111',
    permissions: {
      canAccessPos: false,
      canAccessDashboard: false,
      canAccessScale: false,
      canManageProducts: true,
      canManagePurchases: true,
      canAccessDebts: false,
      canAccessCustomers: false,
      canAccessSuppliers: true,
      canManageExpenses: false,
      canViewProfits: false,
      canAccessStagnantExpiry: true,
      canAccessInvoices: false,
      canAccessReports: false,
      canManageUsers: false,
      canManageSettings: false,
      canDeleteSales: false,
      canApplyDiscount: false,
    },
    isActive: true,
    createdAt: new Date().toISOString(),
  },
];

export const defaultSettings: StoreSettings = {
  id: 1,
  storeName: 'سوبرماركت البركة للمواد الغذائية',
  storePhone: '0550 12 34 56',
  storeAddress: 'شارع فلسطين التجاري - بجانب محطة الحافلات',
  storeCurrency: 'د.ج', // Algerian Dinar by default (can be changed to SAR, EGP, USD, etc. in Settings)
  taxRate: 0,
  receiptHeader: 'أهلاً وسهلاً بكم في متجر البركة\nجودة عالية وأسعار مناسبة للجميع',
  receiptFooter: 'شكراً لزيارتكم ونسعد بخدمتكم دائماً\nالبضاعة المباعة تستبدل خلال 24 ساعة بإحضار الفاتورة',
  expiryAlertDays: 15,
  stagnantDaysThreshold: 30,
  enableScaleSimulator: true,
  autoPrintReceipt: true,
  paperWidth: '80mm',
  requirePinOnStartup: false,
  startupTab: 'pos',
  autoLockMinutes: 0,
  backupIntervalDays: 7,
  lastBackupDate: new Date().toISOString().split('T')[0],
};
